"""Immutable FR-LIB-001 manifest for the shared preset Food Library."""

from collections.abc import Mapping
from dataclasses import dataclass
from decimal import Decimal
from types import MappingProxyType
from typing import Literal

Category = Literal["vegetable", "fruit", "meat", "egg", "aquatic", "soy", "dairy"]
CanonicalUnit = Literal["g", "kg", "ml", "l", "piece"]
StorageLocation = Literal["FRIDGE", "FREEZER", "PANTRY"]

PRODUCE_NOTE = (
    "Fridge Pal conservative editable starter estimate; inspect freshness and adjust in Admin."
)
PROTEIN_NOTE = (
    "Fridge Pal conservative editable starter estimate based on refrigerated storage guidance; "
    "inspect freshness and adjust in Admin."
)
GROUND_MEAT_NOTE = (
    "Fridge Pal conservative editable starter estimate covering ground or minced meat; inspect "
    "freshness and adjust in Admin."
)
PACKAGED_NOTE = (
    "Fridge Pal conservative editable starter estimate; follow printed package use-by and "
    "storage instructions."
)


@dataclass(frozen=True)
class PresetQuantity:
    """One bilingual quick-fill quantity in a canonical unit."""

    label: Mapping[str, str]
    amount: Decimal
    unit: CanonicalUnit


@dataclass(frozen=True)
class PresetShelfLife:
    """One conservative starter rule for the recommended storage location."""

    storage_location: StorageLocation
    duration_days: int
    source_note: str


@dataclass(frozen=True)
class PresetFood:
    """One database-independent Food Library preset."""

    food_key: str
    names: Mapping[str, str]
    aliases: Mapping[str, tuple[str, ...]]
    category: Category
    visual_key: str
    base_unit: CanonicalUnit
    rounding_increment: Decimal
    package_presets: tuple[PresetQuantity, ...]
    recommended_storage: StorageLocation
    shelf_life: tuple[PresetShelfLife, ...]


def _food(
    *,
    food_key: str,
    name_en: str,
    name_zh: str,
    aliases_en: tuple[str, ...],
    aliases_zh: tuple[str, ...],
    category: Category,
    unit: CanonicalUnit,
    increment: str,
    preset_amounts: tuple[str, ...],
    storage: StorageLocation,
    duration_days: int,
    note: str = PRODUCE_NOTE,
) -> PresetFood:
    labels: tuple[Mapping[str, str], ...] = (
        (MappingProxyType({"en": "Regular amount", "zh-CN": "常用份量"}),)
        if len(preset_amounts) == 1
        else (
            MappingProxyType({"en": "Regular amount", "zh-CN": "常用份量"}),
            MappingProxyType({"en": "Large amount", "zh-CN": "大份"}),
        )
    )
    return PresetFood(
        food_key=food_key,
        names=MappingProxyType({"en": name_en, "zh-CN": name_zh}),
        aliases=MappingProxyType({"en": aliases_en, "zh-CN": aliases_zh}),
        category=category,
        visual_key=food_key,
        base_unit=unit,
        rounding_increment=Decimal(increment),
        package_presets=tuple(
            PresetQuantity(label=labels[index], amount=Decimal(amount), unit=unit)
            for index, amount in enumerate(preset_amounts)
        ),
        recommended_storage=storage,
        shelf_life=(
            PresetShelfLife(
                storage_location=storage,
                duration_days=duration_days,
                source_note=note,
            ),
        ),
    )


VEGETABLES_FUNGI_AROMATICS = (
    _food(
        food_key="spinach",
        name_en="Spinach",
        name_zh="菠菜",
        aliases_en=("spinach leaves",),
        aliases_zh=("波斯菜",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("250", "500"),
        storage="FRIDGE",
        duration_days=3,
    ),
    _food(
        food_key="broccoli",
        name_en="Broccoli",
        name_zh="西兰花",
        aliases_en=("calabrese",),
        aliases_zh=("绿菜花",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("300", "500"),
        storage="FRIDGE",
        duration_days=4,
    ),
    _food(
        food_key="carrots",
        name_en="Carrots",
        name_zh="胡萝卜",
        aliases_en=("carrot",),
        aliases_zh=("红萝卜",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("300", "500"),
        storage="FRIDGE",
        duration_days=14,
    ),
    _food(
        food_key="tomatoes",
        name_en="Tomatoes",
        name_zh="西红柿",
        aliases_en=("tomato",),
        aliases_zh=("番茄",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("400", "800"),
        storage="PANTRY",
        duration_days=5,
    ),
    _food(
        food_key="onion",
        name_en="Onion",
        name_zh="洋葱",
        aliases_en=("yellow onion",),
        aliases_zh=("圆葱",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("300", "600"),
        storage="PANTRY",
        duration_days=30,
    ),
    _food(
        food_key="garlic",
        name_en="Garlic",
        name_zh="大蒜",
        aliases_en=("garlic bulb",),
        aliases_zh=("蒜头",),
        category="vegetable",
        unit="g",
        increment="5",
        preset_amounts=("100", "250"),
        storage="PANTRY",
        duration_days=30,
    ),
    _food(
        food_key="mushrooms",
        name_en="Button mushrooms",
        name_zh="口蘑",
        aliases_en=("white mushrooms",),
        aliases_zh=("白蘑菇",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("200", "400"),
        storage="FRIDGE",
        duration_days=3,
    ),
    _food(
        food_key="frozen-peas",
        name_en="Peas",
        name_zh="豌豆",
        aliases_en=("green peas",),
        aliases_zh=("青豆",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("300", "500"),
        storage="FREEZER",
        duration_days=180,
    ),
    _food(
        food_key="potato",
        name_en="Potato",
        name_zh="土豆",
        aliases_en=("potatoes",),
        aliases_zh=("马铃薯",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("500", "1000"),
        storage="PANTRY",
        duration_days=21,
    ),
    _food(
        food_key="sweet-potato",
        name_en="Sweet potato",
        name_zh="红薯",
        aliases_en=("sweet potatoes",),
        aliases_zh=("地瓜", "番薯"),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("500", "1000"),
        storage="PANTRY",
        duration_days=14,
    ),
    _food(
        food_key="white-radish",
        name_en="White radish",
        name_zh="白萝卜",
        aliases_en=("daikon",),
        aliases_zh=("萝卜",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("500", "1000"),
        storage="FRIDGE",
        duration_days=7,
    ),
    _food(
        food_key="lotus-root",
        name_en="Lotus root",
        name_zh="莲藕",
        aliases_en=("lotus rhizome",),
        aliases_zh=("藕",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("400", "800"),
        storage="FRIDGE",
        duration_days=5,
    ),
    _food(
        food_key="chinese-yam",
        name_en="Chinese yam",
        name_zh="山药",
        aliases_en=("nagaimo",),
        aliases_zh=("淮山",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("400", "800"),
        storage="FRIDGE",
        duration_days=10,
    ),
    _food(
        food_key="chinese-cabbage",
        name_en="Chinese cabbage",
        name_zh="大白菜",
        aliases_en=("napa cabbage",),
        aliases_zh=("白菜",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("500", "1000"),
        storage="FRIDGE",
        duration_days=7,
    ),
    _food(
        food_key="baby-cabbage",
        name_en="Baby cabbage",
        name_zh="娃娃菜",
        aliases_en=("baby napa cabbage",),
        aliases_zh=("小白菜心",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("300", "600"),
        storage="FRIDGE",
        duration_days=5,
    ),
    _food(
        food_key="bok-choy",
        name_en="Bok choy",
        name_zh="上海青",
        aliases_en=("pak choi",),
        aliases_zh=("青菜", "小油菜"),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("300", "500"),
        storage="FRIDGE",
        duration_days=3,
    ),
    _food(
        food_key="lettuce",
        name_en="Lettuce",
        name_zh="生菜",
        aliases_en=("leaf lettuce",),
        aliases_zh=("叶生菜",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("250", "500"),
        storage="FRIDGE",
        duration_days=3,
    ),
    _food(
        food_key="chinese-leaf-lettuce",
        name_en="Chinese leaf lettuce",
        name_zh="油麦菜",
        aliases_en=("a-choy",),
        aliases_zh=("油荬菜",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("300", "500"),
        storage="FRIDGE",
        duration_days=3,
    ),
    _food(
        food_key="cabbage",
        name_en="Cabbage",
        name_zh="卷心菜",
        aliases_en=("green cabbage",),
        aliases_zh=("包菜", "圆白菜"),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("500", "1000"),
        storage="FRIDGE",
        duration_days=10,
    ),
    _food(
        food_key="celery",
        name_en="Celery",
        name_zh="芹菜",
        aliases_en=("celery stalks",),
        aliases_zh=("西芹",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("300", "600"),
        storage="FRIDGE",
        duration_days=5,
    ),
    _food(
        food_key="celtuce",
        name_en="Celtuce",
        name_zh="莴笋",
        aliases_en=("stem lettuce",),
        aliases_zh=("莴苣",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("400", "800"),
        storage="FRIDGE",
        duration_days=7,
    ),
    _food(
        food_key="cucumber",
        name_en="Cucumber",
        name_zh="黄瓜",
        aliases_en=("cucumbers",),
        aliases_zh=("青瓜",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("400", "800"),
        storage="FRIDGE",
        duration_days=5,
    ),
    _food(
        food_key="eggplant",
        name_en="Eggplant",
        name_zh="茄子",
        aliases_en=("aubergine",),
        aliases_zh=("紫茄",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("400", "800"),
        storage="FRIDGE",
        duration_days=4,
    ),
    _food(
        food_key="green-pepper",
        name_en="Green pepper",
        name_zh="青椒",
        aliases_en=("green bell pepper",),
        aliases_zh=("菜椒",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("300", "600"),
        storage="FRIDGE",
        duration_days=5,
    ),
    _food(
        food_key="cauliflower",
        name_en="Cauliflower",
        name_zh="菜花",
        aliases_en=("flowering cabbage",),
        aliases_zh=("花椰菜",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("400", "800"),
        storage="FRIDGE",
        duration_days=5,
    ),
    _food(
        food_key="pumpkin",
        name_en="Pumpkin",
        name_zh="南瓜",
        aliases_en=("squash",),
        aliases_zh=("倭瓜",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("500", "1000"),
        storage="PANTRY",
        duration_days=30,
    ),
    _food(
        food_key="winter-melon",
        name_en="Winter melon",
        name_zh="冬瓜",
        aliases_en=("wax gourd",),
        aliases_zh=("白瓜",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("500", "1000"),
        storage="FRIDGE",
        duration_days=5,
    ),
    _food(
        food_key="green-beans",
        name_en="Green beans",
        name_zh="四季豆",
        aliases_en=("string beans",),
        aliases_zh=("芸豆",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("300", "500"),
        storage="FRIDGE",
        duration_days=4,
    ),
    _food(
        food_key="shiitake",
        name_en="Shiitake",
        name_zh="香菇",
        aliases_en=("shiitake mushrooms",),
        aliases_zh=("冬菇",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("200", "400"),
        storage="FRIDGE",
        duration_days=4,
    ),
    _food(
        food_key="enoki",
        name_en="Enoki",
        name_zh="金针菇",
        aliases_en=("enoki mushrooms",),
        aliases_zh=("金菇",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("200", "400"),
        storage="FRIDGE",
        duration_days=3,
    ),
    _food(
        food_key="ginger",
        name_en="Ginger",
        name_zh="生姜",
        aliases_en=("ginger root",),
        aliases_zh=("姜",),
        category="vegetable",
        unit="g",
        increment="5",
        preset_amounts=("100", "250"),
        storage="FRIDGE",
        duration_days=14,
    ),
    _food(
        food_key="scallion",
        name_en="Scallion",
        name_zh="大葱",
        aliases_en=("green onion",),
        aliases_zh=("葱",),
        category="vegetable",
        unit="g",
        increment="5",
        preset_amounts=("100", "250"),
        storage="FRIDGE",
        duration_days=5,
    ),
    _food(
        food_key="chives",
        name_en="Chinese chives",
        name_zh="韭菜",
        aliases_en=("garlic chives",),
        aliases_zh=("细叶韭菜", "jiucai"),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("200", "400"),
        storage="FRIDGE",
        duration_days=3,
    ),
    _food(
        food_key="zucchini",
        name_en="Zucchini",
        name_zh="西葫芦",
        aliases_en=("courgette",),
        aliases_zh=("角瓜",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("400", "800"),
        storage="FRIDGE",
        duration_days=5,
    ),
    _food(
        food_key="loofah",
        name_en="Loofah",
        name_zh="丝瓜",
        aliases_en=("luffa gourd",),
        aliases_zh=("水瓜",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("400", "800"),
        storage="FRIDGE",
        duration_days=4,
    ),
    _food(
        food_key="bitter-melon",
        name_en="Bitter melon",
        name_zh="苦瓜",
        aliases_en=("bitter gourd",),
        aliases_zh=("凉瓜",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("400", "800"),
        storage="FRIDGE",
        duration_days=4,
    ),
    _food(
        food_key="corn",
        name_en="Fresh corn",
        name_zh="鲜玉米",
        aliases_en=("sweet corn",),
        aliases_zh=("玉米棒",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("400", "800"),
        storage="FRIDGE",
        duration_days=3,
    ),
    _food(
        food_key="bean-sprouts",
        name_en="Bean sprouts",
        name_zh="豆芽",
        aliases_en=("sprouts",),
        aliases_zh=("豆芽菜",),
        category="vegetable",
        unit="g",
        increment="10",
        preset_amounts=("250", "500"),
        storage="FRIDGE",
        duration_days=2,
    ),
)

FRUITS = (
    _food(
        food_key="apple",
        name_en="Apple",
        name_zh="苹果",
        aliases_en=("apples",),
        aliases_zh=("红富士苹果", "pingguo"),
        category="fruit",
        unit="piece",
        increment="1",
        preset_amounts=("4", "8"),
        storage="FRIDGE",
        duration_days=14,
    ),
    _food(
        food_key="banana",
        name_en="Banana",
        name_zh="香蕉",
        aliases_en=("bananas",),
        aliases_zh=("蕉",),
        category="fruit",
        unit="piece",
        increment="1",
        preset_amounts=("4", "8"),
        storage="PANTRY",
        duration_days=4,
    ),
    _food(
        food_key="orange",
        name_en="Orange",
        name_zh="橙子",
        aliases_en=("sweet orange",),
        aliases_zh=("甜橙",),
        category="fruit",
        unit="piece",
        increment="1",
        preset_amounts=("4", "8"),
        storage="FRIDGE",
        duration_days=14,
    ),
    _food(
        food_key="mandarin",
        name_en="Mandarin",
        name_zh="橘子",
        aliases_en=("mandarin orange",),
        aliases_zh=("柑橘",),
        category="fruit",
        unit="piece",
        increment="1",
        preset_amounts=("6", "12"),
        storage="FRIDGE",
        duration_days=10,
    ),
    _food(
        food_key="pear",
        name_en="Pear",
        name_zh="梨",
        aliases_en=("pears",),
        aliases_zh=("梨子",),
        category="fruit",
        unit="piece",
        increment="1",
        preset_amounts=("4", "8"),
        storage="FRIDGE",
        duration_days=10,
    ),
    _food(
        food_key="grapes",
        name_en="Grapes",
        name_zh="葡萄",
        aliases_en=("table grapes",),
        aliases_zh=("鲜葡萄",),
        category="fruit",
        unit="g",
        increment="10",
        preset_amounts=("500", "1000"),
        storage="FRIDGE",
        duration_days=5,
    ),
    _food(
        food_key="watermelon",
        name_en="Watermelon",
        name_zh="西瓜",
        aliases_en=("water melon",),
        aliases_zh=("鲜西瓜",),
        category="fruit",
        unit="g",
        increment="50",
        preset_amounts=("1000", "2000"),
        storage="PANTRY",
        duration_days=5,
    ),
    _food(
        food_key="cantaloupe",
        name_en="Cantaloupe",
        name_zh="哈密瓜",
        aliases_en=("muskmelon",),
        aliases_zh=("甜瓜",),
        category="fruit",
        unit="g",
        increment="50",
        preset_amounts=("1000", "2000"),
        storage="PANTRY",
        duration_days=5,
    ),
    _food(
        food_key="strawberry",
        name_en="Strawberry",
        name_zh="草莓",
        aliases_en=("strawberries",),
        aliases_zh=("士多啤梨", "caomei"),
        category="fruit",
        unit="g",
        increment="10",
        preset_amounts=("250", "500"),
        storage="FRIDGE",
        duration_days=2,
    ),
    _food(
        food_key="blueberries",
        name_en="Blueberries",
        name_zh="蓝莓",
        aliases_en=("blueberry",),
        aliases_zh=("越橘",),
        category="fruit",
        unit="g",
        increment="5",
        preset_amounts=("125", "250"),
        storage="FRIDGE",
        duration_days=5,
    ),
    _food(
        food_key="peach",
        name_en="Peach",
        name_zh="桃",
        aliases_en=("peaches",),
        aliases_zh=("桃子",),
        category="fruit",
        unit="piece",
        increment="1",
        preset_amounts=("4", "8"),
        storage="FRIDGE",
        duration_days=3,
    ),
    _food(
        food_key="mango",
        name_en="Mango",
        name_zh="芒果",
        aliases_en=("mangoes",),
        aliases_zh=("檬果",),
        category="fruit",
        unit="piece",
        increment="1",
        preset_amounts=("2", "4"),
        storage="PANTRY",
        duration_days=4,
    ),
    _food(
        food_key="kiwi",
        name_en="Kiwi",
        name_zh="猕猴桃",
        aliases_en=("kiwifruit",),
        aliases_zh=("奇异果",),
        category="fruit",
        unit="piece",
        increment="1",
        preset_amounts=("4", "8"),
        storage="FRIDGE",
        duration_days=7,
    ),
    _food(
        food_key="dragon-fruit",
        name_en="Dragon fruit",
        name_zh="火龙果",
        aliases_en=("pitaya",),
        aliases_zh=("红龙果",),
        category="fruit",
        unit="piece",
        increment="1",
        preset_amounts=("2", "4"),
        storage="PANTRY",
        duration_days=5,
    ),
    _food(
        food_key="pineapple",
        name_en="Pineapple",
        name_zh="菠萝",
        aliases_en=("ananas",),
        aliases_zh=("凤梨",),
        category="fruit",
        unit="piece",
        increment="1",
        preset_amounts=("1", "2"),
        storage="PANTRY",
        duration_days=3,
    ),
    _food(
        food_key="pomelo",
        name_en="Pomelo",
        name_zh="柚子",
        aliases_en=("pummelo",),
        aliases_zh=("文旦",),
        category="fruit",
        unit="piece",
        increment="1",
        preset_amounts=("1", "2"),
        storage="PANTRY",
        duration_days=14,
    ),
    _food(
        food_key="lychee",
        name_en="Lychee",
        name_zh="荔枝",
        aliases_en=("litchi",),
        aliases_zh=("鲜荔枝", "lizhi"),
        category="fruit",
        unit="g",
        increment="10",
        preset_amounts=("500", "1000"),
        storage="PANTRY",
        duration_days=2,
    ),
    _food(
        food_key="lemon",
        name_en="Lemon",
        name_zh="柠檬",
        aliases_en=("lemons",),
        aliases_zh=("黄柠檬", "ningmeng"),
        category="fruit",
        unit="piece",
        increment="1",
        preset_amounts=("3", "6"),
        storage="FRIDGE",
        duration_days=14,
    ),
)

MEAT_EGGS_AQUATIC = (
    _food(
        food_key="eggs",
        name_en="Eggs",
        name_zh="鸡蛋",
        aliases_en=("shell eggs",),
        aliases_zh=("鲜鸡蛋",),
        category="egg",
        unit="piece",
        increment="1",
        preset_amounts=("6", "12"),
        storage="FRIDGE",
        duration_days=21,
        note=PROTEIN_NOTE,
    ),
    _food(
        food_key="chicken-breast",
        name_en="Chicken breast",
        name_zh="鸡胸肉",
        aliases_en=("chicken fillet",),
        aliases_zh=("鸡胸",),
        category="meat",
        unit="g",
        increment="10",
        preset_amounts=("300", "600"),
        storage="FRIDGE",
        duration_days=1,
        note=PROTEIN_NOTE,
    ),
    _food(
        food_key="chicken-thigh",
        name_en="Chicken thigh",
        name_zh="鸡腿",
        aliases_en=("chicken leg",),
        aliases_zh=("鸡大腿",),
        category="meat",
        unit="g",
        increment="10",
        preset_amounts=("400", "800"),
        storage="FRIDGE",
        duration_days=1,
        note=PROTEIN_NOTE,
    ),
    _food(
        food_key="pork",
        name_en="Pork",
        name_zh="猪肉",
        aliases_en=("fresh pork",),
        aliases_zh=("鲜猪肉",),
        category="meat",
        unit="g",
        increment="10",
        preset_amounts=("500", "1000"),
        storage="FRIDGE",
        duration_days=1,
        note=GROUND_MEAT_NOTE,
    ),
    _food(
        food_key="beef",
        name_en="Beef",
        name_zh="牛肉",
        aliases_en=("fresh beef",),
        aliases_zh=("鲜牛肉",),
        category="meat",
        unit="g",
        increment="10",
        preset_amounts=("500", "1000"),
        storage="FRIDGE",
        duration_days=1,
        note=GROUND_MEAT_NOTE,
    ),
    _food(
        food_key="lamb",
        name_en="Lamb",
        name_zh="羊肉",
        aliases_en=("mutton",),
        aliases_zh=("鲜羊肉",),
        category="meat",
        unit="g",
        increment="10",
        preset_amounts=("500", "1000"),
        storage="FRIDGE",
        duration_days=1,
        note=GROUND_MEAT_NOTE,
    ),
    _food(
        food_key="duck",
        name_en="Duck",
        name_zh="鸭肉",
        aliases_en=("fresh duck",),
        aliases_zh=("鲜鸭肉",),
        category="meat",
        unit="g",
        increment="10",
        preset_amounts=("500", "1000"),
        storage="FRIDGE",
        duration_days=1,
        note=PROTEIN_NOTE,
    ),
    _food(
        food_key="fish",
        name_en="Fish",
        name_zh="鱼",
        aliases_en=("fresh fish",),
        aliases_zh=("鲜鱼",),
        category="aquatic",
        unit="g",
        increment="10",
        preset_amounts=("500", "1000"),
        storage="FRIDGE",
        duration_days=1,
        note=PROTEIN_NOTE,
    ),
    _food(
        food_key="shrimp",
        name_en="Shrimp",
        name_zh="虾",
        aliases_en=("prawns",),
        aliases_zh=("鲜虾",),
        category="aquatic",
        unit="g",
        increment="10",
        preset_amounts=("300", "500"),
        storage="FRIDGE",
        duration_days=3,
        note=PROTEIN_NOTE,
    ),
    _food(
        food_key="crab",
        name_en="Crab",
        name_zh="螃蟹",
        aliases_en=("fresh crab",),
        aliases_zh=("鲜蟹",),
        category="aquatic",
        unit="g",
        increment="10",
        preset_amounts=("500", "1000"),
        storage="FRIDGE",
        duration_days=1,
        note=PROTEIN_NOTE,
    ),
)

SOY_CHILLED = (
    _food(
        food_key="tofu",
        name_en="Tofu",
        name_zh="豆腐",
        aliases_en=("bean curd",),
        aliases_zh=("水豆腐",),
        category="soy",
        unit="g",
        increment="10",
        preset_amounts=("300", "500"),
        storage="FRIDGE",
        duration_days=3,
        note=PACKAGED_NOTE,
    ),
    _food(
        food_key="dried-tofu",
        name_en="Dried tofu",
        name_zh="豆干",
        aliases_en=("dried bean curd", "pressed tofu"),
        aliases_zh=("香干",),
        category="soy",
        unit="g",
        increment="10",
        preset_amounts=("200", "400"),
        storage="FRIDGE",
        duration_days=5,
        note=PACKAGED_NOTE,
    ),
    _food(
        food_key="milk",
        name_en="Milk",
        name_zh="牛奶",
        aliases_en=("fresh milk",),
        aliases_zh=("鲜奶",),
        category="dairy",
        unit="ml",
        increment="50",
        preset_amounts=("500", "1000"),
        storage="FRIDGE",
        duration_days=5,
        note=PACKAGED_NOTE,
    ),
    _food(
        food_key="yogurt",
        name_en="Yogurt",
        name_zh="酸奶",
        aliases_en=("yoghurt",),
        aliases_zh=("发酵乳",),
        category="dairy",
        unit="g",
        increment="10",
        preset_amounts=("200", "500"),
        storage="FRIDGE",
        duration_days=5,
        note=PACKAGED_NOTE,
    ),
)

FOOD_LIBRARY_CATALOG: tuple[PresetFood, ...] = (
    *VEGETABLES_FUNGI_AROMATICS,
    *FRUITS,
    *MEAT_EGGS_AQUATIC,
    *SOY_CHILLED,
)
